### ISSUE TITLE
Cannot use ZfcDatagrid\Column\DataPopulation\Object as Object because 'Object'

### ISSUE THREAD

**Issue by ThaDafinser** [zfc-datagrid/zfc-datagrid#38]
_From @kokspflanze on August 20, 2017 20:32_

in php 7.2 we get following error

````
Cannot use ZfcDatagrid\Column\DataPopulation\Object as Object because 'Object'
````

looks like we have to rename that class.

for me personal `Phpobject` looks wrong to name it like that, but i have no other idea=(

_Copied from original issue: ThaDafinser/ZfcDatagrid#283_

**Comment by kokspflanze** [comment]
`DataObject` could be also possible @ZeinEddin what you say?

**Comment by ZeinEddin** [comment]
`DataObject` is a good choice... as this better describes what it have.

**Comment by kokspflanze** [comment]
done with https://github.com/zfc-datagrid/zfc-datagrid/pull/42
