### ISSUE TITLE
Configuration conflict when set non-default cache adapter

### ISSUE THREAD

**Issue by olexp** [zfc-datagrid/zfc-datagrid#47]
Exception thrown when I try to set memcache adapter for ZfcDatagrid in my app:

Zend\Stdlib\Exception\BadMethodCallException: The option "cache_dir" does not have a callable "setCacheDir" ("setcachedir") setter method which must be defined in C:\zend\zf2app\vendor\zendframework\zend-stdlib\src\AbstractOptions.php:110

I am trying to configure adapter in my local config/autoload/zfcdatagrid.local.php
```php
            'adapter' => [
                'name' => Zend\Cache\Storage\Adapter\Memcache::class,
                'options' => [
                    'ttl' => 720000, // cache with 200 hours,
                    'servers' => [['host' => '127.0.0.1']],
                ],
            ],
```

Default configuration in module.config.php
```php
            'adapter' => [
                'name'    => 'Filesystem',
                'options' => [
                    'ttl'       => 720000, // cache with 200 hours,
                    'cache_dir' => 'data/ZfcDatagrid',
                ],
            ],
```

When all configurations loaded by Zend Framework, adapter settings are merged and 'cache_dir' is set for Memcache adapter which leads to exception about setter. I temporary commented 'cache_dir' in vendor. Could you fix or suggest permanent solution for this issue.

**Comment by kokspflanze** [comment]
i will check it next week, hope its okay for you

**Comment by kokspflanze** [comment]
hi @olexp can you test the bugfix?

composer.json

````
"zfc-datagrid/zfc-datagrid": "dev-bugfix47 as 1.9999",
````

tell me your result=)

**Comment by olexp** [comment]
Configuration constructed as expected. Grid works without issues.
