### ISSUE TITLE
Allow changing column type's `filterDefaultOperation`

### ISSUE THREAD

**Issue by halfpastfouram** [zfc-datagrid/zfc-datagrid#52]
The column types are pretty strict when it comes to the `filterDefaultOperation`. If you want to change that operator you're gonna have to create your own, custom type. That's a bit too strict if you ask me so I want to propose the following change:

Allow changing the column type's `filterDefaultOperation` with a setter. I believe there is no harm in doing so and it makes the column type that more flexible and more easy to use.

I'll be making a PR for this.

**Comment by kokspflanze** [comment]
merged
