### ISSUE TITLE
Drop support for PHP 5.6 and 7.0

### ISSUE THREAD

**Issue by halfpastfouram** [zfc-datagrid/zfc-datagrid#54]
This might be an unpopular opinion, but hear me out. Both PHP 5.6 and 7.0 will be completely unsupported by PHP in [three months from now](http://php.net/supported-versions.php). The next release of this project should no longer support these versions of PHP.

The current stable version works fine on both 5.6 and 7.0 so there wouldn't be any loss to current users. It is imperative to keep focus on the support of PHP 7.1 and 7.2, however. Dropping the support for PHP 5.6 and 7.0 in the next release will in no way harm the project.

**Comment by kokspflanze** [comment]
short answer, yes it will be 7.1+. but no time in last months for it.
my current project dont use it. but i will add it, this or next week.

**Comment by halfpastfouram** [comment]
Alright, good to hear. If you need any help, just add new issues and label them with "help wanted".

**Comment by kokspflanze** [comment]
https://github.com/zfc-datagrid/zfc-datagrid/pull/63 =)
